import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Pokémon Roundness Research</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen w-screen flex flex-col justify-center items-center relative">
        <div className="text-2xl text-center">Which Pokémon is the roundest?</div>
        <div className="p-2"></div>
        <div className="border rounded p-8 flex justify-between max-w-2xl items-center">
          <div className="w-16 h-16 bg-pink-400"></div>
          <div className="p-8">vs.</div>
          <div className="w-16 h-16 bg-pink-400"></div>
        </div>
      </div>
    </>
  );
};

export default Home;

