import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";

import { api } from "../utils/api";
import { getOptionsForVote } from "../utils/pokedex";

const Home: NextPage = () => {
  const [firstNationalNumber, setFirstNationalNumber] = useState<number>();
  const [secondNationalNumber, setSecondNationalNumber] = useState<number>();

  useEffect(() => {
    const [first, second] = getOptionsForVote();

    setFirstNationalNumber(first);
    setSecondNationalNumber(second);
  }, []);

  const firstPokemon = api.index.getPokemonByNationalNumber.useQuery({
    nationalNumber: firstNationalNumber
  });

  const secondPokemon = api.index.getPokemonByNationalNumber.useQuery({
    nationalNumber: secondNationalNumber
  });

  if (firstPokemon.isLoading || secondPokemon.isLoading) return null;

  return (
    <>
      <Head>
        <title>Pokémon Roundness Research</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen w-screen flex flex-col justify-center items-center relative">
        <div className="text-2xl text-center">Which Pokémon is the roundest?</div>
        <div className="p-2" />
        <div className="border rounded p-8 flex justify-between max-w-2xl items-center">
          <div className="w-64 h-64 flex flex-col">
            <img src={firstPokemon.data?.sprites.front_default} className="w-full" />
            <div className="text-xl text-center capitalize mt-[-2rem]">{firstPokemon.data?.name}</div>
          </div>
          <div className="p-8">vs.</div>
          <div className="w-64 h-64 flex flex-col">
            <img src={secondPokemon.data?.sprites.front_default} className="w-full" />
            <div className="text-xl text-center capitalize mt-[-2rem]">{secondPokemon.data?.name}</div>
          </div>
          <div className="p-2" />
        </div>
      </div>
    </>
  );
};

export default Home;

